### ISSUE TITLE
Incompatibility between EFCore and SqlClient instrumentation libs

### ISSUE THREAD

**Issue by andrembpontes** [open-telemetry/opentelemetry-dotnet-contrib#178]
There are incompatibilities between:

- OpenTelemetry.Instrumentation.SqlClient v1.0.0-rc8
- OpenTelemetry.Contrib.Instrumentation.EntityFrameworkCore v1.0.0-beta2

# Repro steps:

1. Create an empty project
2. Add EFCore + OpenTelemetry instrumentation libs (EFCore + SqlClient)
3. Do any request using EFCore DbContext

# Expected behavior
Both EFCore + SqlClient spans should be correctly reported with the SqlClient one created as a child of EFCore span.

# Actual behavior
SqlClient spans are created as children of EFCore ones, yet EFCore spans are never completed and therefore never reported. Then, resulting in SqlClient spans pointing to a non-existing parent span ID.

# Explanation
Both SqlClient and EFCore intrumentation libs rely on AsyncLocal mechanism to correctly start/enrich/complete their spans. However when the database operation is completed both diagnostic events are triggered and there is no order guarantee between both listeners.

Most of the times EFCore code runs before SqlClient has the opportunity to stop the current span. When EFCore lib reaches this point:

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/9373eb54d52ef43b9e0cb2284f86f668cad1dbc2/src/OpenTelemetry.Contrib.Instrumentation.EntityFrameworkCore/Implementation/EntityFrameworkDiagnosticListener.cs#L197 

since the `activity` is still the SqlClient span, the `EntityFrameworkCoreCommandExecuted` is ignored and the span is never completed.

There is a similar issue reported [I44](https://github.com/opentracing-contrib/csharp-netcore/issues/44) in OpenTracing lib before they released a fix [PR82](https://github.com/opentracing-contrib/csharp-netcore/pull/82)

# Possible solution

The most obvious solution is to stop relying on AsyncLocal and start using some kind of local data struct to store those references, similar to what was done in OpenTracing lib. I'll try to create a PR with this approach.

Thank you in advance for your time!

**Comment by andrembpontes** [comment]
I managed to submit a PR with the fix. It was tested locally and it's working as expected. I'm waiting for feedback

PR: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/179

**Comment by prochnowc** [comment]
@cijothomas @eddynaka I dont know who maintains this lib. but may it possible to review the PR and get the fix merged/released ? It would be really nice to get EF Core AND Sql Client instrumentation together.

**Comment by NatMarchand** [comment]
Hi there ! Still encountering the issue. Is there anything we can do to mitigate ?

**Comment by saulosagtransfero** [comment]
Is this still an issue?

**Comment by NatMarchand** [comment]
Yes it is

**Comment by martincostello** [comment]
I think #2829 should have resolved this.

**Comment by NatMarchand** [comment]
Yes it does !
